config/routes.rb
Chars::Application.routes.draw do
  resources :shiftmaps

  get "charactercounts/index"

  resources :keystrokes

  resources :charmaps

  resources :characters

  resources :projects do
    resources :datafiles
  end

end

app/models/datafile.rb
class Datafile < ActiveRecord::Base
  belongs_to :project
  has_many :characters

  attr_accessible :name, :status
end

app/controllers/datafiles_controller.rb
class DatafilesController < ApplicationController
  # GET /datafiles
  # GET /datafiles.json
  def index
    @project = Project.find(params[:project_id])
    @datafiles = @project.datafiles.all
#    @datafiles = Datafile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datafiles }
    end
  end

  # GET /datafiles/1
  # GET /datafiles/1.json
  def show
    @datafile = Datafile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datafile }
    end
  end

  # GET /datafiles/new
  # GET /datafiles/new.json
  def new
    @datafile = Datafile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datafile }
    end
  end

  # GET /datafiles/1/edit
  def edit
    @datafile = Datafile.find(params[:id])
  end

  # POST /datafiles
  # POST /datafiles.json
  def create
    @datafile = Datafile.new(params[:datafile])

    respond_to do |format|
      if @datafile.save
        format.html { redirect_to @datafile, notice: 'Datafile was successfully created.' }
        format.json { render json: @datafile, status: :created, location: @datafile }
      else
        format.html { render action: "new" }
        format.json { render json: @datafile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datafiles/1
  # PUT /datafiles/1.json
  def update
    @datafile = Datafile.find(params[:id])

    respond_to do |format|
      if @datafile.update_attributes(params[:datafile])
        format.html { redirect_to @datafile, notice: 'Datafile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datafile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datafiles/1
  # DELETE /datafiles/1.json
  def destroy
    @datafile = Datafile.find(params[:id])
    @datafile.destroy

    respond_to do |format|
      format.html { redirect_to datafiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/datafiles_helper.rb
module DatafilesHelper
end

app/views/datafiles/_form.html.erb
<%= form_for(@datafile) do |f| %>
  <% if @datafile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datafile.errors.count, "error") %> prohibited this datafile from being saved:</h2>

      <ul>
      <% @datafile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datafiles/edit.html.erb
<h1>Editing datafile</h1>

<%= render 'form' %>

<%= link_to 'Show', @datafile %> |
<%= link_to 'Back', datafiles_path %>

app/views/datafiles/index.html.erb
<h1>Listing datafiles for Project: 
  <%= @project.name %>
</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datafiles.each do |datafile| %>
  <tr>
    <td><%= datafile.name %></td>
    <td><%= datafile.status %></td>
    <td><%= link_to 'Show', project_datafile_path(@project.id, datafile.id) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/datafiles/new.html.erb
<h1>New datafile</h1>

<%= render 'form' %>

<%= link_to 'Back', datafiles_path %>

app/views/datafiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @datafile.name %>
</p>

<p>
  <b>Status:</b>
  <%= @datafile.status %>
</p>


<%= link_to 'Edit', edit_datafile_path(@datafile) %> |
<%= link_to 'Back', datafiles_path %>