config/routes.rb
Chars::Application.routes.draw do
  resources :shiftmaps

  get "charactercounts/index"

  resources :keystrokes

  resources :charmaps

  resources :characters

  resources :projects do
    resources :datafiles
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :datafiles

  attr_accessible :archive, :name
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def get_character_counts
    cc = Charactercounts.group("keystroke").select("keystroke, sum(count) as count")
    count_map = {}
    Keystroke.order("\"order\"").map do |ks|
      count = cc.detect { |c| c.keystroke == ks.keystroke }
      count_map[ks.keystroke] = count && count.count || 0
    end
    count_map
  end
  def get_shift_counts
    sc = Shiftcounts.group("keystroke").select("keystroke, sum(count) as count")
    count_map = {}
    Keystroke.order("\"order\"").map do |ks|
      count = sc.detect { |c| c.keystroke == ks.keystroke }
      count_map[ks.keystroke] = count && count.count || 0
    end
    count_map
  end


  def get_project_character_counts p_id
    cc = Charactercounts.where(:project => Project.find(p_id).name)
    count_map = {}
    Keystroke.order("\"order\"").map do |ks|
      count = cc.detect { |c| c.keystroke == ks.keystroke }
      count_map[ks.keystroke] = count && count.count || 0
    end
    count_map
  end
  def get_project_shift_counts p_id
    sc = Shiftcounts.where(:project => Project.find(p_id).name)

    count_map = {}
    Keystroke.order("\"order\"").map do |ks|
      count = sc.detect { |c| c.keystroke == ks.keystroke }
      count_map[ks.keystroke] = count && count.count || 0
    end
    count_map
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :archive %><br />
    <%= f.text_field :archive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<% charactercounts = get_character_counts %>
<% shiftcounts = get_shift_counts %>
<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "character_count_chart",
        type: "column"
      },
      title: {
        text: "Keystrokes by Finger"
      },
      xAxis: {
        categories: [
          <%= charactercounts.collect {|cc| "'" + cc[0] + "'" }.join(",").html_safe %>
        ]
      },
      yAxis: {
        title: {
          text: "count"
        }
      },
      series: [{
        name: "count",
        data: [
          <%= charactercounts.collect {|cc| cc[1] }.join(",").html_safe %>
           ]
      } , {
        name: "shiftcount", 
        data: [
          <%= shiftcounts.collect {|cc| cc[1] }.join(",").html_safe %>
         ]
      }]
    });
  });
</script>

<div id="character_count_chart" style="width:560px; height:300px;"></div>
<table>
  <tr>
    <th>Name</th>
    <th>Archive</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.archive %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
    <td><%= link_to 'Project Files', project_datafiles_path(project) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Archive:</b>
  <%= @project.archive %>
</p>


<% charactercounts = get_project_character_counts @project.id %>
<% shiftcounts = get_project_shift_counts @project.id %>
<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "character_count_chart",
        type: "column"
      },
      title: {
        text: "character counts by finger"
      },
      xAxis: {
        categories: [
          <%= charactercounts.collect {|cc| "'" + cc[0] + "'" }.join(",").html_safe %>
        ]
      },
      yAxis: {
        title: {
          text: "count"
        }
      },
      series: [{
        name: "count",
        data: [
          <%= charactercounts.collect {|cc| cc[1] }.join(",").html_safe %>
           ]
      } , {
        name: "shiftcount", 
        data: [
          <%= shiftcounts.collect {|cc| cc[1] }.join(",").html_safe %>
         ]
      }]
    });
  });
</script>

<div id="character_count_chart" style="width:560px; height:300px;"></div>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>