config/routes.rb
Chars::Application.routes.draw do
  resources :shiftmaps

  get "charactercounts/index"

  resources :keystrokes

  resources :charmaps

  resources :characters

  resources :projects do
    resources :datafiles
  end

end

app/models/shiftmap.rb
class Shiftmap < ActiveRecord::Base
  attr_accessible :keystroke, :letter
end

app/controllers/shiftmaps_controller.rb
class ShiftmapsController < ApplicationController
  # GET /shiftmaps
  # GET /shiftmaps.json
  def index
    @shiftmaps = Shiftmap.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shiftmaps }
    end
  end

  # GET /shiftmaps/1
  # GET /shiftmaps/1.json
  def show
    @shiftmap = Shiftmap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shiftmap }
    end
  end

  # GET /shiftmaps/new
  # GET /shiftmaps/new.json
  def new
    @shiftmap = Shiftmap.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shiftmap }
    end
  end

  # GET /shiftmaps/1/edit
  def edit
    @shiftmap = Shiftmap.find(params[:id])
  end

  # POST /shiftmaps
  # POST /shiftmaps.json
  def create
    @shiftmap = Shiftmap.new(params[:shiftmap])

    respond_to do |format|
      if @shiftmap.save
        format.html { redirect_to @shiftmap, notice: 'Shiftmap was successfully created.' }
        format.json { render json: @shiftmap, status: :created, location: @shiftmap }
      else
        format.html { render action: "new" }
        format.json { render json: @shiftmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shiftmaps/1
  # PUT /shiftmaps/1.json
  def update
    @shiftmap = Shiftmap.find(params[:id])

    respond_to do |format|
      if @shiftmap.update_attributes(params[:shiftmap])
        format.html { redirect_to @shiftmap, notice: 'Shiftmap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shiftmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shiftmaps/1
  # DELETE /shiftmaps/1.json
  def destroy
    @shiftmap = Shiftmap.find(params[:id])
    @shiftmap.destroy

    respond_to do |format|
      format.html { redirect_to shiftmaps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shiftmaps_helper.rb
module ShiftmapsHelper
end

app/views/shiftmaps/_form.html.erb
<%= form_for(@shiftmap) do |f| %>
  <% if @shiftmap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shiftmap.errors.count, "error") %> prohibited this shiftmap from being saved:</h2>

      <ul>
      <% @shiftmap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :letter %><br />
    <%= f.text_field :letter %>
  </div>
  <div class="field">
    <%= f.label :keystroke %><br />
    <%= f.text_field :keystroke %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shiftmaps/edit.html.erb
<h1>Editing shiftmap</h1>

<%= render 'form' %>

<%= link_to 'Show', @shiftmap %> |
<%= link_to 'Back', shiftmaps_path %>

app/views/shiftmaps/index.html.erb
<h1>Listing shiftmaps</h1>

<table>
  <tr>
    <th>Letter</th>
    <th>Keystroke</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shiftmaps.each do |shiftmap| %>
  <tr>
    <td><%= shiftmap.letter %></td>
    <td><%= shiftmap.keystroke %></td>
    <td><%= link_to 'Show', shiftmap %></td>
    <td><%= link_to 'Edit', edit_shiftmap_path(shiftmap) %></td>
    <td><%= link_to 'Destroy', shiftmap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shiftmap', new_shiftmap_path %>

app/views/shiftmaps/new.html.erb
<h1>New shiftmap</h1>

<%= render 'form' %>

<%= link_to 'Back', shiftmaps_path %>

app/views/shiftmaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Letter:</b>
  <%= @shiftmap.letter %>
</p>

<p>
  <b>Keystroke:</b>
  <%= @shiftmap.keystroke %>
</p>


<%= link_to 'Edit', edit_shiftmap_path(@shiftmap) %> |
<%= link_to 'Back', shiftmaps_path %>